# Generated by Django 4.2.7 on 2023-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='gender',
            field=models.CharField(choices=[('Comédia', 'Comédia'), ('Terror', 'Terror'), ('Drama', 'Drama'), ('Romance', 'Romance')], max_length=255),
        ),
    ]
